#!/bin/bash
# Reads version from package.json and writes src/generated/version.ts
VERSION=$(node -p "require('./package.json').version")

# Validate semver (int.int.int)
if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
  echo "ERROR: Invalid semver version in package.json: \"$VERSION\"" >&2
  exit 1
fi

mkdir -p src/generated
TMPFILE=$(mktemp src/generated/version.ts.XXXXXX)
cat > "$TMPFILE" <<EOF
// Auto-generated by generate-version.sh — do not edit
export const AUTH_CLIENT_SDK_VERSION = "$VERSION" as const;
export default AUTH_CLIENT_SDK_VERSION;
EOF
mv "$TMPFILE" src/generated/version.ts
