#!/bin/bash
# Reads version from package.json and writes src/generated/version.ts
VERSION=$(node -p "require('./package.json').version")

# Validate semver (int.int.int)
if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
  echo "ERROR: Invalid semver version in package.json: \"$VERSION\"" >&2
  exit 1
fi

# Remove stale generated file if it exists
rm -f src/generated/version.ts

mkdir -p src/generated
echo "// Auto-generated by generate-version.sh — do not edit" > src/generated/version.ts
echo "export const AUTH_CLIENT_SDK_VERSION = \"$VERSION\" as const;" >> src/generated/version.ts
echo "export default AUTH_CLIENT_SDK_VERSION;" >> src/generated/version.ts
