// The auth server's own OpenAPI document, GET /api/openapi.json, generated by
// @schemavaults/openapi-operations from the operation catalogue in
// auth-server/src/lib/api/operations/. Pins the document's shape and the
// auth metadata of a few representative operations so the per-route
// declarations cannot silently drift from what the route guards enforce.

import { getAuthServerAppIdFromCypressEnv } from "@schemavaults/cypress-e2e-auth-tests-helper-commands";

interface OpenApiOperationObject {
  operationId?: string;
  summary?: string;
  tags?: string[];
  security?: Record<string, string[]>[];
  "x-schemavaults-auth"?: {
    public: boolean;
    schemes: string[];
    routeGuard: "authenticated" | "admin" | null;
    requiredScopes: string[];
  };
}

interface OpenApiDocumentLike {
  openapi: string;
  info: { title: string; version: string; description?: string };
  servers?: { url: string }[];
  tags?: { name: string; description?: string }[];
  paths: Record<string, Record<string, OpenApiOperationObject>>;
  components?: { securitySchemes?: Record<string, { type: string; in?: string; name?: string }> };
}

// Module marker: keeps this spec's top-level interfaces file-scoped.
export {};

const SESSION_SCHEMES = [
  "schemavaults-refresh-token-cookie",
  "schemavaults-access-token-cookie",
  "schemavaults-access-token",
];

describe("GET /api/openapi.json (auth server)", () => {
  it("serves an OpenAPI 3.1 document describing the whole API", () => {
    cy.request<OpenApiDocumentLike>("/api/openapi.json").then((response) => {
      expect(response.status).to.eq(200);
      expect(response.headers["content-type"]).to.include("application/json");
      const doc = response.body;
      expect(doc.openapi).to.eq("3.1.0");
      expect(doc.info.title).to.be.a("string").and.not.be.empty;
      expect(doc.info.version).to.match(/^\d+\.\d+\.\d+/);
      expect(doc.servers?.[0]?.url).to.eq(Cypress.env("AUTH_SERVER_URL"));

      // Every route family of the auth server is present.
      expect(Object.keys(doc.paths)).to.include.members([
        "/api/auth/login",
        "/api/auth/register",
        "/api/auth/whoami/{client_app_id}",
        "/api/auth/logout/{client_app_id}",
        "/api/oidc/token",
        "/api/oidc/authorize",
        "/api/oidc/userinfo",
        "/api/oidc/openid-configuration",
        "/api/oidc/jwks",
        "/api/user/profile",
        "/api/user/mfa/status",
        "/api/me/organizations",
        "/api/me/invitations",
        "/api/apps",
        "/api/apps/{app_id}",
        "/api/apps/{app_id}/service-account",
        "/api/apis",
        "/api/apis/{api_server_id}/connect_app/{client_app_id}",
        "/api/organizations",
        "/api/organizations/{organization_id}/invitations/{invitation_id}",
        "/api/admin/settings/{key}",
        "/api/admin/users/{uid}",
        "/api/jwks/{audience}",
        "/api/resource-server/apis/{api_server_id}/allowed-origins",
        "/api/environment",
        "/api/config/branding",
      ]);
      // The document does not describe itself.
      expect(doc.paths).to.not.have.property("/api/openapi.json");

      // Every operation has an id, a summary, one tag and auth metadata.
      const declaredTags = new Set((doc.tags ?? []).map((tag) => tag.name));
      for (const [path, methods] of Object.entries(doc.paths)) {
        for (const [method, operation] of Object.entries(methods)) {
          const label = `${method.toUpperCase()} ${path}`;
          expect(operation.operationId, `${label} operationId`).to.be.a("string").and.not.be.empty;
          expect(operation.summary, `${label} summary`).to.be.a("string").and.not.be.empty;
          expect(operation.tags, `${label} tags`).to.have.length(1);
          expect(declaredTags.has(operation.tags![0]!), `${label} tag declared`).to.be.true;
          expect(operation["x-schemavaults-auth"], `${label} x-schemavaults-auth`).to.be.an("object");
        }
      }
    });
  });

  it("declares the session credential schemes and the auth level of representative operations", () => {
    cy.request<OpenApiDocumentLike>("/api/openapi.json").then(({ body: doc }) => {
      const schemes = doc.components?.securitySchemes ?? {};
      for (const name of SESSION_SCHEMES) {
        expect(schemes, name).to.have.property(name);
      }
      expect(schemes["schemavaults-access-token"]?.type).to.eq("http");
      expect(schemes["schemavaults-refresh-token-cookie"]?.type).to.eq("apiKey");
      expect(schemes["schemavaults-refresh-token-cookie"]?.in).to.eq("cookie");
      expect(schemes).to.have.property("schemavaults-jwks-access-assertion");

      // A session-guarded operation accepts every session scheme, in order.
      const profile = doc.paths["/api/user/profile"]?.get;
      expect(profile?.security?.map((entry) => Object.keys(entry)[0])).to.deep.eq(SESSION_SCHEMES);
      expect(profile?.["x-schemavaults-auth"]).to.deep.include({
        public: false,
        routeGuard: "authenticated",
        requiredScopes: [],
      });

      // Admin operations are marked as such.
      const usersList = doc.paths["/api/admin/users/list"]?.get;
      expect(usersList?.["x-schemavaults-auth"]?.routeGuard).to.eq("admin");
      const settings = doc.paths["/api/admin/settings/{key}"]?.patch;
      expect(settings?.["x-schemavaults-auth"]?.routeGuard).to.eq("admin");

      // Public operations carry no security requirement.
      for (const [path, method] of [
        ["/api/auth/login", "post"],
        ["/api/oidc/token", "post"],
        ["/api/environment", "get"],
      ] as const) {
        const operation = doc.paths[path]?.[method];
        expect(operation?.["x-schemavaults-auth"]?.public, `${method} ${path} public`).to.eq(true);
        expect(operation?.security ?? [], `${method} ${path} security`).to.deep.eq([]);
      }

      // whoami additionally accepts the per-client-app session cookie.
      const whoami = doc.paths["/api/auth/whoami/{client_app_id}"]?.get;
      expect(whoami?.["x-schemavaults-auth"]?.schemes).to.include(
        "schemavaults-client-app-refresh-token-cookie",
      );

      // Resource-server endpoints require a JWKS access assertion.
      const jwks = doc.paths["/api/jwks/{audience}"]?.get;
      expect(jwks?.["x-schemavaults-auth"]?.schemes).to.deep.eq(["schemavaults-jwks-access-assertion"]);
    });
  });

  it("is readable without a session, and unknown API paths still 404", () => {
    cy.clearCookies();
    cy.request({ url: "/api/openapi.json", failOnStatusCode: false })
      .its("status")
      .should("eq", 200);
    cy.request({ url: "/api/does-not-exist", failOnStatusCode: false })
      .its("status")
      .should("eq", 404);
    // The app id in the document's whoami example path is a placeholder;
    // the real one still resolves.
    cy.request({ url: `/api/auth/whoami/${getAuthServerAppIdFromCypressEnv()}`, failOnStatusCode: false })
      .its("status")
      .should("eq", 401);
  });
});
