import { z, requireAuth, withOpenApi } from "@schemavaults/openapi-operations";
import { mfaCodeOnlyBodySchema } from "@schemavaults/auth-common";
import { defineOperation } from "@/lib/api/context";
import { sessionSchemes } from "@/lib/api/auth-schemes";
import { MfaFactorRemoved, mfaFactorIdParam } from "@/lib/api/domain-schemas/mfa";
import { ErrorResponse, sessionErrorResponses, validationErrorResponse } from "@/lib/api/schemas";
import { API_TAGS } from "@/lib/api/tags";
import { MfaRegistry } from "@/lib/auth-db";
import captureServerException from "@/lib/captureServerException";
import { verifyTotpCode } from "@/lib/mfa";
import { sendMfaSecurityAlertEmail } from "@/lib/mfa/send-mfa-security-alert-email";

const ROUTE = "/api/user/mfa/totp/{factor_id}";

export const removeTotpFactor = defineOperation({
  method: "delete",
  path: ROUTE,
  summary: "Remove a TOTP factor",
  description:
    "Deletes one of the caller's authenticator-app factors (verified or still pending). The request must carry a current code from that very factor as proof of control. Removing the last verified factor also discards the account's recovery codes. A security alert e-mail is sent.",
  tags: [API_TAGS.mfa],
  auth: requireAuth({ schemes: sessionSchemes }),
  request: {
    params: z.object({ factor_id: mfaFactorIdParam }),
    body: {
      lenientContentType: true,
      schema: withOpenApi(mfaCodeOnlyBodySchema, "MfaRemoveTotpFactorRequest"),
      description: "A current 6-digit code generated by the factor being removed.",
    },
  },
  responses: {
    200: { description: "The factor was removed", schema: MfaFactorRemoved },
    ...validationErrorResponse,
    401: {
      description: "The code did not match the factor (or no valid session was presented)",
      schema: ErrorResponse,
    },
    403: sessionErrorResponses[403],
    404: { description: "No such factor for the caller", schema: ErrorResponse },
    500: { description: "Failed to remove the factor", schema: ErrorResponse },
  },
  handler: async (ctx) => {
    const user = ctx.auth.user!;
    const { db, redis } = ctx.context;
    const { factor_id } = ctx.params;
    const { code } = ctx.body;

    const mfaRegistry = new MfaRegistry(db);

    try {
      // Authorize the destructive change with a current TOTP code from the
      // factor being removed — proving the caller controls it. One targeted
      // lookup against the named factor rather than trying every enrolled
      // factor's secret. Works for an unverified (partially-enrolled) factor
      // too, since its secret is the only credential available.
      const factor = await mfaRegistry.getFactorWithSecretById({ uid: user.uid, factor_id });
      if (!factor) {
        return ctx.json(404, { success: false, message: "Factor not found" });
      }
      if (!verifyTotpCode({ secret: factor.secret, code })) {
        return ctx.json(401, { success: false, message: "Invalid TOTP code" });
      }

      // Delete this factor and (if it was the last verified factor) wipe
      // recovery codes too.
      const verifiedSummaries = await mfaRegistry.listVerifiedFactorsForUser(user.uid);
      const isLastVerifiedFactor =
        factor.row.verified &&
        verifiedSummaries.length === 1 &&
        verifiedSummaries[0]?.factor_id === factor_id;
      if (isLastVerifiedFactor) {
        await mfaRegistry.deleteAllFactorsForUser(user.uid);
      } else {
        await mfaRegistry.deleteFactor({ uid: user.uid, factor_id });
      }

      await sendMfaSecurityAlertEmail({
        to: user.email,
        action: "removed",
        db,
        redis,
      });

      return ctx.json(200, { success: true });
    } catch (e: unknown) {
      await captureServerException(db, e, {
        op_name: "DELETE_factor_handler",
        route: ROUTE,
        uid: user.uid,
      });
      return ctx.json(500, { success: false, message: "Failed to remove factor" });
    }
  },
});
