const CODEGEN_MARKER_PREFIX = "// code generated by @schemavaults/auth-server-sdk:";

const CODEGEN_MARKER_REGEX =
  /^\/\/ code generated by @schemavaults\/auth-server-sdk:.+$/;

export function getCodegenMarkerComment(): string {
  const version = typeof __SDK_VERSION__ === "string" ? __SDK_VERSION__ : "unknown";
  return `${CODEGEN_MARKER_PREFIX}${version}`;
}

export function hasCodegenMarker(firstLine: string): boolean {
  return CODEGEN_MARKER_REGEX.test(firstLine);
}

export function prependCodegenMarker(content: string): string {
  return `${getCodegenMarkerComment()}\n${content}`;
}
