// e2e-spec-durations.ts
//
// How long each spec took in CI, in seconds (Cypress's "Run Finished"
// table; cypress.config.ts prints the same numbers as an
// `[e2e-spec-durations]` JSON line at the end of every run). `e2e --shard`
// uses them only to balance a suite's shards: they never decide which specs
// run. Specs missing here are estimated at their suite's median, so a new
// spec needs no entry; refresh a suite's numbers when its shards drift apart.

export const E2E_SPEC_DURATIONS_SECONDS: Readonly<
  Record<string, Readonly<Record<string, number>>>
> = {
  account: {
    "UserProfileCard.cy.ts": 76,
  },
  admin: {
    "AdminCannotDisableSelf.cy.ts": 2,
    "AdminClientErrorsPage.cy.ts": 26,
    "AdminErrorsApi.cy.ts": 6,
    "AdminErrorsPage.cy.ts": 34,
    "AdminInviteCodesApi.cy.ts": 21,
    "AdminMfaResetApi.cy.ts": 31,
    "AdminResendVerificationAlreadyVerified.cy.ts": 25,
    "AdminServerTracesApi.cy.ts": 10,
    "AdminSettingsApi.cy.ts": 9,
    "AdminTracesPage.cy.ts": 23,
    "AdminUserDetailPage.cy.ts": 23,
    "AdminUserLifecycleApi.cy.ts": 101,
    "AdminUserTokensApi.cy.ts": 29,
    "DisablingUserRevokesSessions.cy.ts": 23,
    "RegularUserAdminApiForbidden.cy.ts": 344,
    "RegularUserCannotDeleteUser.cy.ts": 49,
    "RegularUserCannotPromoteToAdmin.cy.ts": 19,
    "ServiceAccountEmailDomainSetting.cy.ts": 18,
  },
  api_contract: {
    "ApiCredentialSources.cy.ts": 93,
    "AppServiceAccountApiLifecycle.cy.ts": 10,
    "AuthServerApiDocsPages.cy.ts": 1,
    "AuthServerOpenApiDocument.cy.ts": 1,
    "AuthenticatedApiResponseShapes.cy.ts": 173,
    "ClientErrorReportsApi.cy.ts": 56,
    "TextPlainJsonBodies.cy.ts": 5,
    "WebauthnEnrollmentOptionsApi.cy.ts": 40,
  },
  apis: {
    "ApiServerDetailPageAddDomain.cy.ts": 31,
    "ApiServers.cy.ts": 22,
    "ApiServersApiValidation.cy.ts": 78,
    "ConnectAppToApi.cy.ts": 166,
    "CreateApiServerOwnerField.cy.ts": 22,
    "DisconnectAppFromApi.cy.ts": 57,
    "NonOrgMemberCannotDeleteApiServer.cy.ts": 25,
    "NonOrgMemberCannotGetApiServer.cy.ts": 26,
    "OrgMemberCannotAddApiServerDomain.cy.ts": 27,
    "UserOwnedApiServers.cy.ts": 45,
  },
  apps: {
    "AppCallbackUrlsApi.cy.ts": 60,
    "AppClientSecretApi.cy.ts": 48,
    "AppDetailPageAddDomain.cy.ts": 30,
    "Apps.cy.ts": 30,
    "AppsApiValidation.cy.ts": 145,
    "AuthServerAppCannotBeExplicitlyAuthorized.cy.ts": 26,
    "CreateAppOwnerField.cy.ts": 26,
    "NonOrgMemberCannotDeleteApp.cy.ts": 24,
    "NonOrgMemberCannotGetApp.cy.ts": 24,
    "OrgMemberCannotAddAppDomain.cy.ts": 27,
    "UserOwnedApps.cy.ts": 56,
  },
  dynamic_client_registration: {
    "DynamicClientRegistration.cy.ts": 162,
  },
  example_resource_server: {
    "ApiServerTokenIntrospection.cy.ts": 36,
    "ClientCredentialsGrant.cy.ts": 19,
    "ConfidentialClientSignIn.cy.ts": 125,
    "ConfidentialClientTokenEndpoint.cy.ts": 2,
    "EmailVerificationRequiredForThirdPartyApps.cy.ts": 197,
    "ExampleResourceServer.cy.ts": 165,
    "ExternalJwksLoad.cy.ts": 50,
    "MfaOAuth2PkceFlow.cy.ts": 121,
    "OAuth2State.cy.ts": 94,
    "OidcTokenIntrospection.cy.ts": 1,
    "OpenApiOperations.cy.ts": 32,
    "OpenidClientSignIn.cy.ts": 124,
    "PlainOAuth2Grant.cy.ts": 57,
    "RedirectUriValidation.cy.ts": 163,
    "WhoamiCorsHeaders.cy.ts": 1,
  },
  login: {
    "DisabledUserLoginBlocked.cy.ts": 54,
    "Login.cy.ts": 51,
    "PkceChallengeExpired.cy.ts": 27,
    "PostLoginRedirectNextHref.cy.ts": 19,
  },
  logout: {
    "Logout.cy.ts": 11,
    "RevokedSessionRejectedByRouteGuards.cy.ts": 10,
    "TokenRevocationOnLogout.cy.ts": 10,
  },
  mfa: {
    "Mfa.cy.ts": 177,
    "MfaLoginChallengeApi.cy.ts": 86,
    "MfaTotpApiLifecycle.cy.ts": 115,
    "WebauthnMfa.cy.ts": 1,
  },
  misc: {
    "AppEnvironmentEndpoint.cy.ts": 1,
    "AuthApiRequestValidation.cy.ts": 115,
    "AuthCorsPreflights.cy.ts": 48,
    "AuthorizationServerMetadata.cy.ts": 1,
    "ConfigBrandingEndpoint.cy.ts": 1,
    "NotFoundPage.cy.ts": 1,
    "OidcAuthorizeValidation.cy.ts": 8,
    "OidcConfidentialClientFlow.cy.ts": 111,
    "OidcDiscoveryAndJwks.cy.ts": 1,
    "OidcTokenEndpointSdkExtensions.cy.ts": 48,
    "OidcTokenEndpointValidation.cy.ts": 1,
    "UnauthenticatedApiRequests.cy.ts": 4,
    "UnauthenticatedRedirects.cy.ts": 7,
  },
  organizations: {
    "AdminAssignMemberDialog.cy.ts": 98,
    "AdminDirectMemberAssignmentApi.cy.ts": 145,
    "DirectMemberAssignmentAuthorization.cy.ts": 519,
    "DuplicatePendingInvitationRejected.cy.ts": 22,
    "InvitationAuthorization.cy.ts": 59,
    "InvitationDeclineApi.cy.ts": 64,
    "InviteExistingMemberRejected.cy.ts": 34,
    "LastOwnerDemotionProtection.cy.ts": 22,
    "MeInvitationsIsolation.cy.ts": 65,
    "MeOrganizationRoleNonMember.cy.ts": 22,
    "MemberRoleApi.cy.ts": 208,
    "NonMemberOrganizationApiAccess.cy.ts": 78,
    "OnlyOwnerCanRevokeInvitation.cy.ts": 75,
    "OrganizationApiValidation.cy.ts": 193,
    "Organizations.cy.ts": 36,
    "RoleUpdateRejectsAdminRole.cy.ts": 17,
    "SystemOrganizationProtection.cy.ts": 2,
    "UserOrganizationsPage.cy.ts": 73,
  },
  refresh_token_rotation: {
    "RefreshTokenRotation.cy.ts": 38,
  },
  register: {
    "EmailCaseInsensitivity.cy.ts": 59,
    "InviteCodes.cy.ts": 14,
    "Register.cy.ts": 1,
    "ServiceAccountEmailDomain.cy.ts": 52,
    "VerifyEmail.cy.ts": 97,
    "VerifyEmailAccountCard.cy.ts": 78,
  },
  reset_password: {
    "PasswordResetRevokesRefreshTokens.cy.ts": 34,
    "PasswordResetRevokesSessionAtRouteGuards.cy.ts": 25,
    "ResetPassword.cy.ts": 118,
  },
  resource_management: {
    "HardcodedResourceDeletionProtection.cy.ts": 3,
    "JwksAccessKeyAuthorization.cy.ts": 210,
    "JwksAccessKeySchemavaultsAuthBlocked.cy.ts": 4,
    "ResourceServerAllowedOrigins.cy.ts": 28,
    "ResourceServerOrganizationMemberRole.cy.ts": 114,
    "ServiceAccountOrganizationMembership.cy.ts": 43,
  },
  superuser: {
    "SuperuserCreation.cy.ts": 31,
  },
  white_label: {
    "WhiteLabelAppId.cy.ts": 17,
    "WhiteLabelBranding.cy.ts": 2,
    "WhiteLabelBrandingApiValidation.cy.ts": 7,
    "WhiteLabelBrandingAssetsAdmin.cy.ts": 16,
    "WhiteLabelEnvGuard.cy.ts": 1,
    "WhiteLabelNotFoundPage.cy.ts": 1,
  },
};
