name: Apply Latest DB Migrations

on:
  workflow_call:
    inputs:
      BUN_VERSION:
        description: "Bun version to use"
        required: true
        type: string
    secrets:
      VERCEL_TOKEN:
        description: "Vercel Token"
        required: true
      VERCEL_PROJECT_ID:
        description: "Vercel Project ID"
        required: true
      VERCEL_ORG_ID:
        description: "Vercel Organization ID"
        required: true
permissions:
  contents: read

jobs:
  Apply-Latest-DB-Migrations:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.BUN_VERSION }}
      - name: Install Dependencies
        run: bun install
      - name: Build Migrations
        run: bun run build:migrations
        working-directory: auth-server
      - name: Build Migrations
        run: bun run build:migrations
        working-directory: auth-server

      # pull .env.production file, use it to connect to the database
      - name: Pull Vercel Environment Information
        run: vercel env pull .env.production --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: auth-server
      - name: Run Migrations
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: /bin/bash ./migrate-db.sh .env.production
        working-directory: auth-server
