name: Main Branch Production C.I. & C.D.
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  BUN_VERSION: 1.3.6
  NODE_VERSION: 24

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  SetupCiCdConfig:
    runs-on: ubuntu-latest
    outputs:
      bun_version: ${{ steps.versions.outputs.bun_version }}
      node_version: ${{ steps.versions.outputs.node_version }}
    steps:
      - name: Set version outputs
        id: versions
        run: |
          echo "bun_version=${{ env.BUN_VERSION }}" >> "$GITHUB_OUTPUT"
          echo "node_version=${{ env.NODE_VERSION }}" >> "$GITHUB_OUTPUT"

  Run-ESLint:
    runs-on: ubuntu-latest
    needs:
      - SetupCiCdConfig
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      - name: Install dependencies
        run: |
          bun install
      - name: Run ESLint with Bun
        run: |
          bun run lint

  Run-Unit-Tests:
    runs-on: ubuntu-latest
    needs:
      - SetupCiCdConfig
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      - name: Install dependencies
        run: |
          bun install
      - name: Run unit tests with bun
        run: |
          bun run test

  Run-E2E-Tests:
    runs-on: ubuntu-latest
    needs:
      - SetupCiCdConfig
      - Run-Unit-Tests
      - Run-ESLint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Run Tests with Docker Compose
        run: |
          /bin/bash ./e2e.sh
        working-directory: tests/e2e-auth-tests
      - name: Check if screenshots directory exists
        id: check_screenshots_existence
        run: |
          if [ -d "tests/e2e-auth-tests/cypress/screenshots/" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        if: always()
      - name: Upload screenshots of failing tests
        uses: actions/upload-artifact@v6
        with:
          name: failed-test-screenshots-${{ github.sha }}
          path: tests/e2e-auth-tests/cypress/screenshots/
          retention-days: 2
        if: always() && steps.check_screenshots_existence.outputs.exists == 'true'

  Deploy-Vercel-Production:
    runs-on: ubuntu-latest
    needs:
      - Run-E2E-Tests
      - Run-Unit-Tests
      - Run-ESLint
      - SetupCiCdConfig
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  Build-Auth-Packages-And-Upload-Tarballs-If-Changed:
    runs-on: ubuntu-latest
    needs:
      - SetupCiCdConfig
      - Run-Unit-Tests
      - Run-ESLint
    outputs:
      auth_ui_tarball_name: ${{ steps.upload-auth-ui.outputs.tarball_name }}
      auth_react_provider_tarball_name: ${{ steps.upload-auth-react-provider.outputs.tarball_name }}
      auth_common_tarball_name: ${{ steps.upload-auth-common.outputs.tarball_name }}
      auth_client_sdk_tarball_name: ${{ steps.upload-auth-client-sdk.outputs.tarball_name }}
      auth_server_sdk_tarball_name: ${{ steps.upload-auth-server-sdk.outputs.tarball_name }}
      jwt_tarball_name: ${{ steps.upload-jwt.outputs.tarball_name }}
      app_definitions_tarball_name: ${{ steps.upload-app-definitions.outputs.tarball_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}

      - name: Install package dependencies
        run: bun install

      # Build all @schemavaults/* packages for publishing
      - name: Build all auth packages
        run: bun run build:packages

      - name: Upload @schemavaults/app-definitions tarball
        id: upload-app-definitions
        uses: ./.github/actions/prepare-package-tarball-if-version-changed
        with:
          package_path: "packages/app-definitions"
          package_name: "@schemavaults/app-definitions"
          bun_version: "${{ needs.SetupCiCdConfig.outputs.bun_version }}"
          node_version: "${{ env.NODE_VERSION }}"
          needs_build: false

      - name: Upload @schemavaults/auth-common tarball
        id: upload-auth-common
        uses: ./.github/actions/prepare-package-tarball-if-version-changed
        with:
          package_path: "packages/auth-common"
          package_name: "@schemavaults/auth-common"
          bun_version: "${{ needs.SetupCiCdConfig.outputs.bun_version }}"
          node_version: "${{ env.NODE_VERSION }}"
          needs_build: false

      - name: Upload @schemavaults/jwt tarball
        id: upload-jwt
        uses: ./.github/actions/prepare-package-tarball-if-version-changed
        with:
          package_path: "packages/jwt"
          package_name: "@schemavaults/jwt"
          bun_version: "${{ needs.SetupCiCdConfig.outputs.bun_version }}"
          node_version: "${{ env.NODE_VERSION }}"
          needs_build: false

      - name: Upload @schemavaults/auth-server-sdk tarball
        id: upload-auth-server-sdk
        uses: ./.github/actions/prepare-package-tarball-if-version-changed
        with:
          package_path: "packages/auth-server-sdk"
          package_name: "@schemavaults/auth-server-sdk"
          bun_version: "${{ needs.SetupCiCdConfig.outputs.bun_version }}"
          node_version: "${{ env.NODE_VERSION }}"
          needs_build: false

      - name: Upload @schemavaults/auth-client-sdk tarball
        id: upload-auth-client-sdk
        uses: ./.github/actions/prepare-package-tarball-if-version-changed
        with:
          package_path: "packages/auth-client-sdk"
          package_name: "@schemavaults/auth-client-sdk"
          bun_version: "${{ needs.SetupCiCdConfig.outputs.bun_version }}"
          node_version: "${{ env.NODE_VERSION }}"
          needs_build: false

      - name: Upload @schemavaults/auth-react-provider tarball
        id: upload-auth-react-provider
        uses: ./.github/actions/prepare-package-tarball-if-version-changed
        with:
          package_path: "packages/auth-react-provider"
          package_name: "@schemavaults/auth-react-provider"
          bun_version: "${{ needs.SetupCiCdConfig.outputs.bun_version }}"
          node_version: "${{ env.NODE_VERSION }}"
          needs_build: false

      - name: Upload @schemavaults/auth-ui tarball
        id: upload-auth-ui
        uses: ./.github/actions/prepare-package-tarball-if-version-changed
        with:
          package_path: "packages/auth-ui"
          package_name: "@schemavaults/auth-ui"
          bun_version: "${{ needs.SetupCiCdConfig.outputs.bun_version }}"
          node_version: "${{ env.NODE_VERSION }}"
          needs_build: false

  Publish-App-Definitions:
    needs:
      - SetupCiCdConfig
      - Build-Auth-Packages-And-Upload-Tarballs-If-Changed
    if: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.app_definitions_tarball_name != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-package-tarball-to-all-registries.yml
    with:
      tarball_name: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.app_definitions_tarball_name }}
      package_path: "packages/app-definitions"
      bun_version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      node_version: ${{ needs.SetupCiCdConfig.outputs.node_version }}
    secrets: inherit

  Publish-Auth-Common:
    needs:
      - SetupCiCdConfig
      - Build-Auth-Packages-And-Upload-Tarballs-If-Changed
    if: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_common_tarball_name != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-package-tarball-to-all-registries.yml
    with:
      tarball_name: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_common_tarball_name }}
      package_path: "packages/auth-common"
      bun_version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      node_version: ${{ needs.SetupCiCdConfig.outputs.node_version }}
    secrets: inherit

  Publish-JWT:
    needs:
      - SetupCiCdConfig
      - Build-Auth-Packages-And-Upload-Tarballs-If-Changed
    if: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.jwt_tarball_name != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-package-tarball-to-all-registries.yml
    with:
      tarball_name: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.jwt_tarball_name }}
      package_path: "packages/jwt"
      bun_version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      node_version: ${{ needs.SetupCiCdConfig.outputs.node_version }}
    secrets: inherit

  Publish-Auth-Server-SDK:
    needs:
      - SetupCiCdConfig
      - Build-Auth-Packages-And-Upload-Tarballs-If-Changed
    if: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_server_sdk_tarball_name != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-package-tarball-to-all-registries.yml
    with:
      tarball_name: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_server_sdk_tarball_name }}
      package_path: "packages/auth-server-sdk"
      bun_version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      node_version: ${{ needs.SetupCiCdConfig.outputs.node_version }}
    secrets: inherit

  Publish-Auth-Client-SDK:
    needs:
      - SetupCiCdConfig
      - Build-Auth-Packages-And-Upload-Tarballs-If-Changed
    if: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_client_sdk_tarball_name != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-package-tarball-to-all-registries.yml
    with:
      tarball_name: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_client_sdk_tarball_name }}
      package_path: "packages/auth-client-sdk"
      bun_version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      node_version: ${{ needs.SetupCiCdConfig.outputs.node_version }}
    secrets: inherit

  Publish-Auth-React-Provider:
    needs:
      - SetupCiCdConfig
      - Build-Auth-Packages-And-Upload-Tarballs-If-Changed
    if: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_react_provider_tarball_name != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-package-tarball-to-all-registries.yml
    with:
      tarball_name: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_react_provider_tarball_name }}
      package_path: "packages/auth-react-provider"
      bun_version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      node_version: ${{ needs.SetupCiCdConfig.outputs.node_version }}
    secrets: inherit

  Publish-Auth-UI:
    needs:
      - SetupCiCdConfig
      - Build-Auth-Packages-And-Upload-Tarballs-If-Changed
    if: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_ui_tarball_name != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish-package-tarball-to-all-registries.yml
    with:
      tarball_name: ${{ needs.Build-Auth-Packages-And-Upload-Tarballs-If-Changed.outputs.auth_ui_tarball_name }}
      package_path: "packages/auth-ui"
      bun_version: ${{ needs.SetupCiCdConfig.outputs.bun_version }}
      node_version: ${{ needs.SetupCiCdConfig.outputs.node_version }}
    secrets: inherit
