name: Publish Package to GitHub Package Registry

on:
  workflow_call:
    inputs:
      tarball_name:
        description: "Name of the tarball containing the packed NPM package (e.g. auth-common.tgz)"
        required: true
        type: string
      package_path:
        description: "Directory of the NPM package to publish (e.g. packages/auth-common)"
        required: true
        type: string
      bun_version:
        description: "Bun version to use"
        required: true
        type: string

permissions:
  packages: write
  contents: read

jobs:
  Publish-Package-To-Github:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun_version }}

      - name: Download package artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.tarball_name }}
          path: ${{ inputs.package_path }}

      - name: Assert package tarball exists at expected location
        working-directory: ./${{ inputs.package_path }}
        run: |
          echo "Working Directory: \"$(pwd)\""
          echo "Working Directory Contents:\n$(ls -la)"
          if [ ! -f ./${{ inputs.tarball_name }} ]; then
            echo "Error: ./${{ inputs.tarball_name }} not found!"
            exit 1
          fi

      - name: Configure .npmrc file
        working-directory: ./${{ inputs.package_path }}
        run: |
          if [ -f ./.npmrc ]; then
            echo "Error: Expected .npmrc file to not exist yet!"
            exit 1
          fi
          echo "@schemavaults:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:username=\${SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_USER}" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=\${SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_TOKEN}" >> .npmrc

      - name: Publish package to GitHub NPM registry
        working-directory: ./${{ inputs.package_path }}
        run: |
          TARBALL_PATH="$(pwd)/${{ inputs.tarball_name }}"
          echo "Publishing tarball at: \"$TARBALL_PATH\""
          if [ ! -f "$TARBALL_PATH" ]; then
            echo "Error: $TARBALL_PATH not found!"
            exit 1
          fi
          if [ ! -f .npmrc ]; then
            echo "Error: .npmrc configuration file not found!"
            exit 1
          else
            echo "Contents of .npmrc:\n"
            cat .npmrc
            echo "\n"
          fi
          if [ -z "$SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_USER" ]; then
            echo "Missing user to publish with from environment variables!"
            exit 1
          fi
          if [ -z "$SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_TOKEN" ]; then
            echo "Missing auth token to publish with from secrets!"
            exit 1
          fi
          echo "Variables SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_USER and SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_TOKEN appear to be set."

          SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_USER=$SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_USER SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_TOKEN=$SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_TOKEN bun publish "$TARBALL_PATH" --registry=https://npm.pkg.github.com --access public
        env:
          SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_USER: ${{ github.actor }}
          SCHEMAVAULTS_GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
