name: Publish Package to NPMJS Registry

on:
  workflow_call:
    inputs:
      tarball_name:
        description: "Name of the tarball containing the packed NPM package (e.g. auth-common.tgz)"
        required: true
        type: string
      package_path:
        description: "Directory of the NPM package to publish (e.g. packages/auth-common)"
        required: true
        type: string
      node_version:
        description: "NodeJs version to use"
        required: true
        type: string

jobs:
  Publish-Package-To-Npmjs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: "https://registry.npmjs.org"

      - name: Download package tarball artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.tarball_name }}
          path: ${{ inputs.package_path }}

      - name: Assert package tarball exists at expected location
        working-directory: ${{ inputs.package_path }}
        run: |
          echo "Working Directory: \"$(pwd)\""
          echo "Working Directory Contents:\n$(ls -la)"
          if [ ! -f ./${{ inputs.tarball_name }} ]; then
            echo "Error: ./${{ inputs.tarball_name }} not found!"
            exit 1
          fi

      - name: Publish package to NPMJS registry
        working-directory: ${{ inputs.package_path }}
        run: npm publish ./${{ inputs.tarball_name }} --provenance
