name: Run E2E Tests

on:
  workflow_call:
    inputs:
      BUN_VERSION:
        description: "What version of Bun should we use?"
        required: true
        type: string

jobs:
  Run-Authentication-Flows-E2E-Tests:
    uses: ./.github/workflows/run-e2e-test-suite.yml
    with:
      BUN_VERSION: ${{ inputs.BUN_VERSION }}
      test-suite-name: authentication_flows
  Run-Resource-Management-E2E-Tests:
    uses: ./.github/workflows/run-e2e-test-suite.yml
    with:
      BUN_VERSION: ${{ inputs.BUN_VERSION }}
      test-suite-name: resource_management
  Run-Superuser-E2E-Tests:
    uses: ./.github/workflows/run-e2e-test-suite.yml
    with:
      BUN_VERSION: ${{ inputs.BUN_VERSION }}
      test-suite-name: superuser
  Run-Example-Resource-Server-E2E-Tests:
    uses: ./.github/workflows/run-e2e-test-suite.yml
    with:
      BUN_VERSION: ${{ inputs.BUN_VERSION }}
      test-suite-name: example_resource_server
  Run-Miscellaneous-E2E-Tests:
    uses: ./.github/workflows/run-e2e-test-suite.yml
    with:
      BUN_VERSION: ${{ inputs.BUN_VERSION }}
      test-suite-name: misc
