name: Run E2E Tests

on:
  workflow_call:
    inputs:
      BUN_VERSION:
        description: "What version of Bun should we use?"
        required: true
        type: string

jobs:
  Run-Core-E2E-Tests:
    uses: ./.github/workflows/run-e2e-test-suite.yml
    with:
      BUN_VERSION: ${{ inputs.BUN_VERSION }}
      test-suite-name: core
  Run-Superuser-E2E-Tests:
    uses: ./.github/workflows/run-e2e-test-suite.yml
    with:
      BUN_VERSION: ${{ inputs.BUN_VERSION }}
      test-suite-name: superuser
