name: Run E2E Tests

on:
  workflow_call:

jobs:
  Run-E2E-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Run Tests with Docker Compose
        run: |
          /bin/bash ./e2e.sh
        working-directory: tests/e2e-auth-tests
      - name: Check if screenshots directory exists
        id: check_screenshots_existence
        run: |
          if [ -d "tests/e2e-auth-tests/cypress/screenshots/" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        if: always()
      - name: Upload screenshots of failing tests
        uses: actions/upload-artifact@v6
        with:
          name: failed-test-screenshots-${{ github.sha }}
          path: tests/e2e-auth-tests/cypress/screenshots/
          retention-days: 2
        if: always() && steps.check_screenshots_existence.outputs.exists == 'true'
